### ISSUE TITLE
Problem with this code

### ISSUE THREAD

**Issue by batata004** [DzikuVx/ppm_encoder#2]
Hi!

First thank you for providing a good PPM good. However I am trying to use this code with CC3D to simulate the PPM it expects to receive. I configured CHANNEL 1 at CC3D to PPM and used your code (just changed the "sigPin") but LIBREPILOT never recognizes the pulses. I also tried to invert the onState but does not work too.

Would you mind checking why CC3D does not recognize your PPM pulses?

**Comment by DzikuVx** [comment]
I'm using this code like this: https://github.com/DzikuVx/rc_fake_ppm_receiver/blob/master/rc_fake_ppm_receiver.ino and all my flight controllers recognizes signal. Tested on Flip32, SPracingF3 using Cleanflight, INAV and Betaflight

**Comment by batata004** [comment]
Yeap, that code worked perfectly, thank you so much DzikuVx!
